var page_res = {
	"meter": "meters",
	"kilometer": "kilometers", 
	"mile": "miles",
	"yard": "yards",
	"degree": "degrees",
	"millimeter": "millimeters",
	"inch": "inches",
	"centimeter": "centimeters",
	"decimeter": "decimeters",
	"foot": "feet",
	"square": "square",
	"saveMap": "save map",
	"printMap": "print map",
	"scaleCannotNull": "Map scale cannot be null",
	"tempStr1": "A total number of (",
	"tempStr2": ") records found. The current is the (",
	"tempStr3": ") record.",
	"tempStr4": "A total number of ",
	"tempStr5": "pages found. The current is the ",
	"tempStr6": "page.",
	"queryResult": "Query Result",
	"queryResultNull": "Query result is Null",
	"experssionCanNotNull": "Query experssion cannot be null",
	"networkInfo": "Network Info",
	"arcInfo": "Edge Info",
	"networkAnalystResult": "Network Analysis Result",
	"noNetworkLayer": "No network dataset found",
	"roadLength": "Route length: ",
	"findPathFail": "Failed to find the shortest path. Please check network analysis parameters or specify the from- and to-node again",
	"findTSPPathFail": "Failed to find the TSP path. Please check network analysis parameters or specify the stop nodes again",
	"addEntitySuccess": "Succeeded to add!",
	"addEntityFail": "Failed to add!",
	"updateEntitySuccess": "Succeeded to update!",
	"updateEntityFail": "Failed to update",
	"updatePropertySuccess": "Succeeded to update attributes!",
	"updatePropertyFail": "Failed to update attributes!",
	"deleteEntitySuccess": "Succeeded to delete!",
	"deleteEntityFail": "Failed to delete!",
	"closestFacilityFail": "Failed to find the closest facilities.",
	"choosePoint": "Please select event and facility",
	"serviceAnalystFail": "Failed to find the service area.",
	"invalidValue": "Invalid weight: ",
	"coordinateIllegal": "Invalid coordinates",
	"scaleIllegal": "Invalid scale",
	"setScaleIllegal": "Set Scale Illegal",
	"mapPositionException": "Exception in map positioning",
	"mouseMoveException": "Exception in moving mouse cursor: ",
	"showMenu": 'Display menu',
	"hideMenu": 'Hide menu',
	"one": "Monday",
	"two": "Tuesday",
	"three": "Wednesday",
	"four": "Thursday",
	"five": "Friday",
	"six": "Saturday",
	"sun": "Sunday",
	"year": ".",
	"month": ".",
	"day": " ",
	"week": "",
	"field": "Field",
	"name": " name:",
	"experssion": "Experssion:",
	"color": "Color:",
	"subsection": "Segment ",
	"segmentNumber": "Count",
	"distance": "Segment Length",
	"segmentNumberNull": "The count of segment cannot be null",
	"segmentNumberInteger": "The count of segment must be an integer",
	"inputEffectData": "Please input a valid value",
	"mustMoreThanStartValue": "Must be larger than start value",
	"mustLessThanEndValue": "Must be less than end value",
	"fieldCanNotNull": "The count of fields cannot be null",
	"fieldMustInteger": "The count of fields must be an integer",
	"fieldMustMoreThanZero": "The count of fields must be larger than zero",
	"numberCanNotNull": "The number cannot null"
}