<%@page import="cn.grgbanking.feeltm.config.*"%>
<%@page import="cn.grgbanking.feeltm.util.*"%>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/commontag.tld" prefix="common" %>
<%@ taglib uri="/WEB-INF/pagination_tag.tld" prefix="tm" %>


<html:base/>


